// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: api/server/server.proto

package server_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_Unknown Status = 0
	Status_GOOD    Status = 1
	Status_NORMAL  Status = 2
	Status_BAD     Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Unknown",
		1: "GOOD",
		2: "NORMAL",
		3: "BAD",
	}
	Status_value = map[string]int32{
		"Unknown": 0,
		"GOOD":    1,
		"NORMAL":  2,
		"BAD":     3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_server_server_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_api_server_server_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_api_server_server_proto_rawDescGZIP(), []int{0}
}

type AuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_api_server_server_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_api_server_server_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type StartProcessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessID int32 `protobuf:"varint,1,opt,name=processID,proto3" json:"processID,omitempty"`
}

func (x *StartProcessRequest) Reset() {
	*x = StartProcessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessRequest) ProtoMessage() {}

func (x *StartProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessRequest.ProtoReflect.Descriptor instead.
func (*StartProcessRequest) Descriptor() ([]byte, []int) {
	return file_api_server_server_proto_rawDescGZIP(), []int{2}
}

func (x *StartProcessRequest) GetProcessID() int32 {
	if x != nil {
		return x.ProcessID
	}
	return 0
}

type StartProcessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CameraMetrics *StartProcessResponse_CameraMetrics `protobuf:"bytes,1,opt,name=cameraMetrics,proto3" json:"cameraMetrics,omitempty"`
	ClockMetrics  *StartProcessResponse_ClockMetrics  `protobuf:"bytes,2,opt,name=clockMetrics,proto3" json:"clockMetrics,omitempty"`
}

func (x *StartProcessResponse) Reset() {
	*x = StartProcessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessResponse) ProtoMessage() {}

func (x *StartProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessResponse.ProtoReflect.Descriptor instead.
func (*StartProcessResponse) Descriptor() ([]byte, []int) {
	return file_api_server_server_proto_rawDescGZIP(), []int{3}
}

func (x *StartProcessResponse) GetCameraMetrics() *StartProcessResponse_CameraMetrics {
	if x != nil {
		return x.CameraMetrics
	}
	return nil
}

func (x *StartProcessResponse) GetClockMetrics() *StartProcessResponse_ClockMetrics {
	if x != nil {
		return x.ClockMetrics
	}
	return nil
}

type StartProcessResponse_CameraMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=server_service.Status" json:"status,omitempty"`
}

func (x *StartProcessResponse_CameraMetrics) Reset() {
	*x = StartProcessResponse_CameraMetrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartProcessResponse_CameraMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessResponse_CameraMetrics) ProtoMessage() {}

func (x *StartProcessResponse_CameraMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessResponse_CameraMetrics.ProtoReflect.Descriptor instead.
func (*StartProcessResponse_CameraMetrics) Descriptor() ([]byte, []int) {
	return file_api_server_server_proto_rawDescGZIP(), []int{3, 0}
}

func (x *StartProcessResponse_CameraMetrics) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Unknown
}

type StartProcessResponse_ClockMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pulse       *StartProcessResponse_ClockMetrics_Pulse       `protobuf:"bytes,1,opt,name=pulse,proto3" json:"pulse,omitempty"`
	Temperature *StartProcessResponse_ClockMetrics_Temperature `protobuf:"bytes,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Oxygen      *StartProcessResponse_ClockMetrics_Oxygen      `protobuf:"bytes,3,opt,name=oxygen,proto3" json:"oxygen,omitempty"`
}

func (x *StartProcessResponse_ClockMetrics) Reset() {
	*x = StartProcessResponse_ClockMetrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartProcessResponse_ClockMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessResponse_ClockMetrics) ProtoMessage() {}

func (x *StartProcessResponse_ClockMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessResponse_ClockMetrics.ProtoReflect.Descriptor instead.
func (*StartProcessResponse_ClockMetrics) Descriptor() ([]byte, []int) {
	return file_api_server_server_proto_rawDescGZIP(), []int{3, 1}
}

func (x *StartProcessResponse_ClockMetrics) GetPulse() *StartProcessResponse_ClockMetrics_Pulse {
	if x != nil {
		return x.Pulse
	}
	return nil
}

func (x *StartProcessResponse_ClockMetrics) GetTemperature() *StartProcessResponse_ClockMetrics_Temperature {
	if x != nil {
		return x.Temperature
	}
	return nil
}

func (x *StartProcessResponse_ClockMetrics) GetOxygen() *StartProcessResponse_ClockMetrics_Oxygen {
	if x != nil {
		return x.Oxygen
	}
	return nil
}

type StartProcessResponse_ClockMetrics_Pulse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=server_service.Status" json:"status,omitempty"`
	Value  uint32 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StartProcessResponse_ClockMetrics_Pulse) Reset() {
	*x = StartProcessResponse_ClockMetrics_Pulse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartProcessResponse_ClockMetrics_Pulse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessResponse_ClockMetrics_Pulse) ProtoMessage() {}

func (x *StartProcessResponse_ClockMetrics_Pulse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessResponse_ClockMetrics_Pulse.ProtoReflect.Descriptor instead.
func (*StartProcessResponse_ClockMetrics_Pulse) Descriptor() ([]byte, []int) {
	return file_api_server_server_proto_rawDescGZIP(), []int{3, 1, 0}
}

func (x *StartProcessResponse_ClockMetrics_Pulse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Unknown
}

func (x *StartProcessResponse_ClockMetrics_Pulse) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type StartProcessResponse_ClockMetrics_Temperature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status  `protobuf:"varint,1,opt,name=status,proto3,enum=server_service.Status" json:"status,omitempty"`
	Value  float32 `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StartProcessResponse_ClockMetrics_Temperature) Reset() {
	*x = StartProcessResponse_ClockMetrics_Temperature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartProcessResponse_ClockMetrics_Temperature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessResponse_ClockMetrics_Temperature) ProtoMessage() {}

func (x *StartProcessResponse_ClockMetrics_Temperature) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessResponse_ClockMetrics_Temperature.ProtoReflect.Descriptor instead.
func (*StartProcessResponse_ClockMetrics_Temperature) Descriptor() ([]byte, []int) {
	return file_api_server_server_proto_rawDescGZIP(), []int{3, 1, 1}
}

func (x *StartProcessResponse_ClockMetrics_Temperature) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Unknown
}

func (x *StartProcessResponse_ClockMetrics_Temperature) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type StartProcessResponse_ClockMetrics_Oxygen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status  `protobuf:"varint,1,opt,name=status,proto3,enum=server_service.Status" json:"status,omitempty"`
	Value  float32 `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StartProcessResponse_ClockMetrics_Oxygen) Reset() {
	*x = StartProcessResponse_ClockMetrics_Oxygen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_server_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartProcessResponse_ClockMetrics_Oxygen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessResponse_ClockMetrics_Oxygen) ProtoMessage() {}

func (x *StartProcessResponse_ClockMetrics_Oxygen) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessResponse_ClockMetrics_Oxygen.ProtoReflect.Descriptor instead.
func (*StartProcessResponse_ClockMetrics_Oxygen) Descriptor() ([]byte, []int) {
	return file_api_server_server_proto_rawDescGZIP(), []int{3, 1, 2}
}

func (x *StartProcessResponse_ClockMetrics_Oxygen) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Unknown
}

func (x *StartProcessResponse_ClockMetrics_Oxygen) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_api_server_server_proto protoreflect.FileDescriptor

var file_api_server_server_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x24, 0x0a, 0x0c, 0x41, 0x75, 0x74, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x33, 0x0a,
	0x13, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x49, 0x44, 0x22, 0x8f, 0x06, 0x0a, 0x14, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x0d, 0x63,
	0x61, 0x6d, 0x65, 0x72, 0x61, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x32, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x0d, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x55, 0x0a, 0x0c, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x0c,
	0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x1a, 0x3f, 0x0a, 0x0d,
	0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x2e, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x84, 0x04,
	0x0a, 0x0c, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x4d,
	0x0a, 0x05, 0x70, 0x75, 0x6c, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x2e, 0x50, 0x75, 0x6c, 0x73, 0x65, 0x52, 0x05, 0x70, 0x75, 0x6c, 0x73, 0x65, 0x12, 0x5f, 0x0a,
	0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x3d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x50,
	0x0a, 0x06, 0x6f, 0x78, 0x79, 0x67, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x38,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x2e, 0x4f, 0x78, 0x79, 0x67, 0x65, 0x6e, 0x52, 0x06, 0x6f, 0x78, 0x79, 0x67, 0x65, 0x6e,
	0x1a, 0x4d, 0x0a, 0x05, 0x50, 0x75, 0x6c, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a,
	0x53, 0x0a, 0x0b, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x2e,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x1a, 0x4e, 0x0a, 0x06, 0x4f, 0x78, 0x79, 0x67, 0x65, 0x6e, 0x12, 0x2e,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x2a, 0x34, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x47,
	0x4f, 0x4f, 0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10,
	0x02, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x41, 0x44, 0x10, 0x03, 0x32, 0xb3, 0x01, 0x0a, 0x0d, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x04,
	0x41, 0x75, 0x74, 0x68, 0x12, 0x1b, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x5d, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x23, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x66, 0x5a, 0x64, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75,
	0x6d, 0x34, 0x72, 0x75, 0x2d, 0x63, 0x68, 0x34, 0x6e, 0x2f, 0x6d, 0x61, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x63, 0x79, 0x2f, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x2f, 0x6c, 0x61, 0x62, 0x34, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_server_server_proto_rawDescOnce sync.Once
	file_api_server_server_proto_rawDescData = file_api_server_server_proto_rawDesc
)

func file_api_server_server_proto_rawDescGZIP() []byte {
	file_api_server_server_proto_rawDescOnce.Do(func() {
		file_api_server_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_server_server_proto_rawDescData)
	})
	return file_api_server_server_proto_rawDescData
}

var file_api_server_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_server_server_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_server_server_proto_goTypes = []interface{}{
	(Status)(0),                                           // 0: server_service.Status
	(*AuthRequest)(nil),                                   // 1: server_service.AuthRequest
	(*AuthResponse)(nil),                                  // 2: server_service.AuthResponse
	(*StartProcessRequest)(nil),                           // 3: server_service.StartProcessRequest
	(*StartProcessResponse)(nil),                          // 4: server_service.StartProcessResponse
	(*StartProcessResponse_CameraMetrics)(nil),            // 5: server_service.StartProcessResponse.CameraMetrics
	(*StartProcessResponse_ClockMetrics)(nil),             // 6: server_service.StartProcessResponse.ClockMetrics
	(*StartProcessResponse_ClockMetrics_Pulse)(nil),       // 7: server_service.StartProcessResponse.ClockMetrics.Pulse
	(*StartProcessResponse_ClockMetrics_Temperature)(nil), // 8: server_service.StartProcessResponse.ClockMetrics.Temperature
	(*StartProcessResponse_ClockMetrics_Oxygen)(nil),      // 9: server_service.StartProcessResponse.ClockMetrics.Oxygen
}
var file_api_server_server_proto_depIdxs = []int32{
	5,  // 0: server_service.StartProcessResponse.cameraMetrics:type_name -> server_service.StartProcessResponse.CameraMetrics
	6,  // 1: server_service.StartProcessResponse.clockMetrics:type_name -> server_service.StartProcessResponse.ClockMetrics
	0,  // 2: server_service.StartProcessResponse.CameraMetrics.status:type_name -> server_service.Status
	7,  // 3: server_service.StartProcessResponse.ClockMetrics.pulse:type_name -> server_service.StartProcessResponse.ClockMetrics.Pulse
	8,  // 4: server_service.StartProcessResponse.ClockMetrics.temperature:type_name -> server_service.StartProcessResponse.ClockMetrics.Temperature
	9,  // 5: server_service.StartProcessResponse.ClockMetrics.oxygen:type_name -> server_service.StartProcessResponse.ClockMetrics.Oxygen
	0,  // 6: server_service.StartProcessResponse.ClockMetrics.Pulse.status:type_name -> server_service.Status
	0,  // 7: server_service.StartProcessResponse.ClockMetrics.Temperature.status:type_name -> server_service.Status
	0,  // 8: server_service.StartProcessResponse.ClockMetrics.Oxygen.status:type_name -> server_service.Status
	1,  // 9: server_service.ServerService.Auth:input_type -> server_service.AuthRequest
	3,  // 10: server_service.ServerService.StartProcess:input_type -> server_service.StartProcessRequest
	2,  // 11: server_service.ServerService.Auth:output_type -> server_service.AuthResponse
	4,  // 12: server_service.ServerService.StartProcess:output_type -> server_service.StartProcessResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_server_server_proto_init() }
func file_api_server_server_proto_init() {
	if File_api_server_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_server_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_server_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_server_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartProcessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_server_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartProcessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_server_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartProcessResponse_CameraMetrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_server_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartProcessResponse_ClockMetrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_server_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartProcessResponse_ClockMetrics_Pulse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_server_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartProcessResponse_ClockMetrics_Temperature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_server_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartProcessResponse_ClockMetrics_Oxygen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_server_server_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_server_server_proto_goTypes,
		DependencyIndexes: file_api_server_server_proto_depIdxs,
		EnumInfos:         file_api_server_server_proto_enumTypes,
		MessageInfos:      file_api_server_server_proto_msgTypes,
	}.Build()
	File_api_server_server_proto = out.File
	file_api_server_server_proto_rawDesc = nil
	file_api_server_server_proto_goTypes = nil
	file_api_server_server_proto_depIdxs = nil
}
