version: "3.9"
services:
  db:
    image: postgres:14.0
    environment:
      TZ: 'Europe/Moscow'
      POSTGRES_DB: "db_scum_board"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker-init:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_scum_board"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G