@startuml testDiagram

' Сотрудник

left to right direction
execute as (Выполнить\nрабочий процесс)
chooseProcess as (Выбрать рабочий\nпроцесс из доступных)
enterAcc as (Войти в аккаунт)
replyOnAlert as (Отреагировать на\nпредупреждение\nо нарушении\nтехники безопасности)
fixMistakes as (Исправить нарушиние)
closeAlert as (Закрыть окно\nпредупреждения)
okAlert as (Подтвердить\nпредупреждение)
turnOffAlerts as (Отключить\nпредупреждения)

:Сотрудник: --> (execute)
execute ..> (chooseProcess) : include
execute ..> (enterAcc) : include
execute ..> (replyOnAlert) : extend

replyOnAlert ..> (fixMistakes) : extend
replyOnAlert ..> (closeAlert) : extend
replyOnAlert ..> (okAlert) : extend
replyOnAlert ..> (turnOffAlerts) : extend

enterAcc .> (Выйти из аккаунта) : extend

chooseProcess ..> (Начать РП) : extend
chooseProcess ..> (Приостановить РП) : extend
chooseProcess ..> (Возобновить РП) : extend
chooseProcess ..> (Закончить РП) : extend

' Администратор

manageTaskList as (Управлять\nсписком задач)
createTask as (Создать\nрабочий процесс)
readTask as (Просмотреть\nрабочий процесс)
updateTask as (Обновить\nрабочий процесс)
deleteTask as (Удалить\nрабочий процесс)

watchStatistics as (Отслеживать\nстатистику по\nраб. месту)
productsAmount as (Просмотреть\nкол-во изделий)
alertsAmount as (Просмотреть кол-во\nпредупреждений)
tempGraph as (Просмотреть график\nтемпературы сотрудника)
humidityGraph as (Просмотреть\nграфик влажности)
bpmGraph as (Просмотреть график\nизменения пульса\nсотрудника)
oxygenLvl as (Просмотреть график\nизменения уровня\nкислорода в крови\nсотрудника)

:Администратор: --> (manageTaskList)
manageTaskList ..> (enterAcc) : include
manageTaskList ..> (createTask) : extend
manageTaskList ..> (readTask) : extend
manageTaskList ..> (updateTask) : extend
manageTaskList ..> (deleteTask) : extend

:Администратор: --> (watchStatistics)
watchStatistics ...> (enterAcc) : include
watchStatistics ..> (productsAmount) : extend
watchStatistics ..> (alertsAmount) : extend
watchStatistics ..> (tempGraph) : extend
watchStatistics ..> (humidityGraph) : extend
watchStatistics ..> (bpmGraph) : extend
watchStatistics ..> (oxygenLvl) : extend

@enduml